---
title: "Resources to Help Me Make My First Shiny App"
output: html_notebook
---

# Resources

The [Starbucks data](https://github.com/rfordatascience/tidytuesday/blob/master/data/2021/2021-12-21/readme.md) are from a 2021 Tidy Tuesday. There is also an inspirational [Behance infographic](https://www.behance.net/gallery/58743971/Starbucks-Menu-Infographic-Design).

See the in-built examples in the package folder. There are even examples for uploading (Example 9) and download files (Example 10).

The online version of [Mastering Shiny](https://mastering-shiny.org/index.html) is a key resource.

See the [Shiny website](https://shiny.posit.co/r/getstarted/shiny-basics/lesson1/index.html) for a quick-start guide. The guide provides a way to access the in-built examples through {shiny} in the console:

|                            |                              |
|:-------------------------- |:-----------------------------|
|runExample("01_hello")      | a histogram                  |
|runExample("02_text")       | tables and data frames       |
|runExample("03_reactivity") | a reactive expression        |
|runExample("04_mpg")        | global variables             |
|runExample("05_sliders")    | slider bars                  |
|runExample("06_tabsets")    | tabbed panels                |
|runExample("07_widgets")    | help text and submit buttons |
|runExample("08_html")       | Shiny app built from HTML    |
|runExample("09_upload")     | file upload wizard           |
|runExample("10_download")   | file download wizard         |
|runExample("11_timer")      | an automated timer           |

The Shiny website has a helpful [layout guide](https://shiny.posit.co/r/articles/build/layout-guide/) that explains how to add panels.

The Shiny website also has step-by-step tutorials for creating a basic Shiny app, including how to [source helper scripts](https://shiny.posit.co/r/getstarted/shiny-basics/lesson5/).

This [Introduction to R Shiny](https://www.youtube.com/watch?v=P7T5haMRYwk) tutorial by an Appsilon employee was presented to the Tunis RUG. There is an accompanying [GitHub repository](https://github.com/aniaskrzydlo/intro-to-shiny-hands-on-workshop).

This is an Appsilon article on how to implement [infinite scrolling in a Shiny app](https://appsilon.com/infinite-scrolling-in-r-shiny/).

There was a R-Ladies STL presentation on [dynamic reporting using a Shiny app](https://www.meetup.com/rladies-st-louis/events/282720794/).See the [video tutorial](https://www.youtube.com/watch?v=MvGAstDzLJk) and YouTube and the [project files](https://github.com/winterstat/RLadiesSTL-shinyreports/tree/main) on GitHub; the slides are no longer on the presenter's website.

[*Building Web Apps with R Shiny*](https://debruine.github.io/shinyintro/reports.html) has a chapter on downloadable reports. *Mastering Shiny* has a chapter on uploads and downloads too [(Chapter 9)](https://mastering-shiny.org/action-transfer.html#action-transfer).

See this straightforward [dependent selectInput objects tutorial](https://heds.nz/posts/dependent-selectInputs-shiny/). It was last updated in November 2022. See the [accompanying code on GitLab](https://gitlab.com/hedsnz/hedsnz-public/-/blob/main/r/dependent-selectInputs-shiny.R). This tutorial indicates that the solution will work with both selectInput() and selectizeInput(). The difference being that selectizeInput() has more parameters and allows users to type to search dropdown menu. See more information and examples on the [Shiny website](https://shiny.posit.co/r/articles/build/selectize/) and [selectize.js website](https://selectize.dev/).

[Maya Gans](https://maya.rbind.io/resume) has a great R-Ladies Tunis [A Little JS Goes a Long Way](https://alittlejs.netlify.app/#1) presentation; there is an [accompanying video](https://www.youtube.com/watch?v=a_umFne86K8). She has another presentation highlight the beauty of combining JS and R: [JS + R == Amazing Applications | Understanding HTMLWidgets](https://phuseus-jsandr.netlify.app/#1). Maya is one of the authors of [*JavaScript for Data Science*](https://third-bit.com/js4ds/).

There are materials from a [Web Design for Shiny Devs](https://webdesign4shiny.rinterface.com/) workshop available online. It was hosted by Maya Gans and David Granjon. It provides a nice introduction to {bslib}. There is also a recommendation for an awesome [color picker from Adobe](https://color.adobe.com/create/color-wheel). *

See the R4DS Online Learning Community [companion guide](https://r4ds.github.io/bookclub-shinyui/) to David Granjon's [Outstanding User Interfaces with Shiny](https://unleash-shiny.rinterface.com/index.html).

There is an [Awesome Shiny Extensions](https://github.com/nanxstats/awesome-shiny-extensions) GitHub repository that details extension packages for making Shiny applications extra swanky. 

There is a specific output function for use with {reactable}: [reactableOutput](https://glin.github.io/reactable/reference/reactable-shiny.html).

See this blogpost on [shinyWidgets::pickerInput() function](https://copyprogramming.com/howto/shiny-selectinput-to-select-all-from-dropdown).

Per [this StackOverflow forum](https://stackoverflow.com/questions/74653162/how-to-create-dynamic-filters-in-my-r-shiny-app-to-automatically-update-the-valu), it seems that the functionality I am seeking comes out-of-the-box with [shinyWidgets's SelectizeGroupUI() function](https://dreamrs.github.io/shinyWidgets/reference/selectizeGroup-module.html).

See how to create a [basic pop-up](https://stackoverflow.com/questions/73306444/r-shiny-popup-window-when-hovering-over-icon) in this StackOverflow forum.

Several articles([LinkedIn](https://www.linkedin.com/pulse/shiny-app-r-integrating-filter-multiple-dynamic-conditions-lee-rock/), [RStudio Community](https://community.rstudio.com/t/reactive-filter-using-multiple-inputs-in-shiny/28974), [blog post](https://www.davidsolito.com/post/conditional-drop-down-in-shiny/)) that helped with designing the dataset filtering.

Adding a side panel and pills (as an alternative to tabsets) were easy to add using [{bslib} reference page](https://rstudio.github.io/bslib/reference/navset.html#details) and [Posit Shiny help article](https://shiny.posit.co/r/articles/build/tabsets/) that was updated in January 2024.

Posit has a [Shiny playlist on YouTube](https://www.youtube.com/playlist?list=PL9HYL-VRX0oRbLoj3FyL5zeASU5FMDgVe).

Appsilon has an article on [How to Work with Bootstrap Themes in Shiny](https://appsilon.com/r-shiny-bslib/).

The [{reactable} documentation](https://glin.github.io/reactable/reference/reactableTheme.html) provides a straightforward example for using reactableTheme() to add striped theme and highlight.

[This StackOverflow forum](https://stackoverflow.com/questions/74222616/change-search-bar-text-in-reactable-table-in-r) made changing the reactable placeholder text super simple.

Nicola Rennie gave an awesome R-Ladies Cambridge [talk on creating custom color scales](https://nrennie.rbind.io/talks/rladies-cambridge-ggplot2-colours/) in March 2023.

Geeks for Geeks provides a convenient [list of shapes](https://www.geeksforgeeks.org/how-to-change-the-legend-shape-using-ggplot2-in-r/) available for guide legend.

Cedric Scherer's [A ggplot2 Tutorial for Beautiful Plotting in R](https://www.cedricscherer.com/2019/08/05/a-ggplot2-tutorial-for-beautiful-plotting-in-r/) is full of incredible customizations--as is his [Outlier Conf 2021 presentation](https://www.cedricscherer.com/slides/OutlierConf2021_ggplot-wizardry.pdf).

Allison Horst has a [succinct tutorial on {ggiraph}](https://allisonhorst.github.io/ggiraph-demo/demo.html).

There are [Shiny {ggiraph} examples](https://www.ardata.fr/ggiraph-book/shiny-examples.html) on the documentation site.

The [third edition of the ggplot2 book](https://ggplot2-book.org/scales-colour#sec-legend-layout) helped me discover how to stack the horizontal guide legends using legend.box within theme().

https://stackoverflow.com/questions/62378430/how-to-download-graphs-which-are-dynamic-in-r-shiny

Only a few shapes can have both fill and color (stroke): Shapes 21 to 26. See [this StackOverflow forum](https://stackoverflow.com/questions/15965870/fill-and-border-colour-in-geom-point-scale-colour-manual-in-ggplot)! Remember this if [changing the legend shape](https://stackoverflow.com/questions/27221011/fill-scale-is-not-shown-in-the-legend).


# *Mastering Shiny* Notes

See Chapter 2.2.7 for information on [action buttons](https://mastering-shiny.org/basic-ui.html?#action-buttons), including styling. There is further information on how to configure an action button with an [on-click event](https://mastering-shiny.org/basic-reactivity.html#on-click) in Chapter 3.3.5. It requires use of eventReactive(). See [Chapter 10.1.1](https://mastering-shiny.org/action-dynamic.html?#simple-uses) for easy instructions for creating a reset button using actionButton(). See {shiny} documentation for updateSelectInput() choices to use to clear selections.

[Chapter 3.3.5](https://mastering-shiny.org/basic-reactivity.html#execution-order) notes that, unlike other R code, "the order in which reactive code is run is determined only by the reactive graph, not by its layout in the server function."


